version: '3'
services:
  mongodb:
    image: mongo
    logging:
      driver: none
    networks:
      - demo
    ports:
      - '27017:27017'

  gateway:
    image: node:10
    working_dir: /usr/src/app
    # environment:
    #   MONGO_DATABASE: '${MONGO_DATABASE:-gateway}'
    #   URL_MONGODB: '${URL_MONGODB:-mongodb://mongodb:27017/gateway}'
    env_file:
      - ./gateway/.env
    depends_on:
      - mongodb
    networks:
      - demo
    ports:
      - '8081:8081'
    volumes:
      - './gateway:/usr/src/app'
      - '/root/.npm'
    command: bash -c "npm run docker:dev"

  order:
    image: node:10
    working_dir: /usr/src/app
    # environment:
    #   MONGO_DATABASE: '${MONGO_DATABASE:-gateway}'
    #   URL_MONGODB: '${URL_MONGODB:-mongodb://mongodb:27017/gateway}'
    env_file:
      - ./modules/order/.env
    depends_on:
      - mongodb
    networks:
      - demo
    ports:
      - '8012:8012'
    volumes:
      - './modules/order:/usr/src/app'
      - '/root/.npm'
    command: bash -c "npm run docker:dev"

  # policy:
  #   image: node:10
  #   working_dir: /usr/src/app
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - demo
  #   ports:
  #     - '8082:8082'
  #   volumes:
  #     - './modules/policy:/usr/src/app'
  #     - '/root/.npm'
  #   command: bash -c "npm install && npm run docker:dev"
networks:
  demo:
    driver: bridge
