version: '3'
services:
  mongodb:
    image: mongo
    logging:
      driver: none
    networks:
      - demo
    ports:
      - '27017:27017'

  gateway:
    image: node:10
    working_dir: /usr/src/app
    container_name: 'order-payment-demo_gateway'
    # environment:
    #   MONGO_DATABASE: '${MONGO_DATABASE:-gateway}'
    #   URL_MONGODB: '${URL_MONGODB:-mongodb://mongodb:27017/gateway}'
    env_file:
      - ./gateway/.env
    depends_on:
      - mongodb
    networks:
      - demo
    ports:
      - '8081:8081'
    volumes:
      - './gateway:/usr/src/app'
      - '/root/.npm'
    command: bash -c "npm run docker:dev"

  order:
    image: node:10
    working_dir: /usr/src/app
    container_name: 'order-payment-demo_order'
    # environment:
    #   MONGO_DATABASE: '${MONGO_DATABASE:-gateway}'
    #   URL_MONGODB: '${URL_MONGODB:-mongodb://mongodb:27017/gateway}'
    env_file:
      - ./modules/order/.env
    depends_on:
      - mongodb
    networks:
      - demo
    ports:
      - '8012:8012'
    volumes:
      - './modules/order:/usr/src/app'
      - '/root/.npm'
    command: bash -c "npm run docker:dev"

  payment:
    image: node:10
    working_dir: /usr/src/app
    container_name: 'order-payment-demo_payment'
    # environment:
    #   MONGO_DATABASE: '${MONGO_DATABASE:-gateway}'
    #   URL_MONGODB: '${URL_MONGODB:-mongodb://mongodb:27017/gateway}'
    env_file:
      - ./modules/payment/.env
    depends_on:
      - mongodb
    networks:
      - demo
    ports:
      - '8031:8031'
    volumes:
      - './modules/payment:/usr/src/app'
      - '/root/.npm'
    command: bash -c "npm run docker:dev"

  mongo-seeding:
    image: node:10
    container_name: order-payment-demo_mongo_seeding
    volumes:
      - './gateway:/usr/src/app/gateway'
      - './modules/order:/usr/src/app/order'
    depends_on:
      - mongodb
    #Here is the command we use to initiate the mongodb seeding
    command: >
      sh -c " npm install -g mongo-seeding-cli
      && cd /usr/src/app/gateway/seed && npm i && seed -u 'mongodb://mongodb:27017/gateway' --drop-database /usr/src/app/gateway/seed/data
      && cd /usr/src/app/order/seed && npm i && seed -u 'mongodb://mongodb:27017/orders' --drop-database /usr/src/app/order/seed/data"
    networks:
      - demo

networks:
  demo:
    driver: bridge
